// <auto-generated />
using System;
using FinancesAppDLL.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinancesAppDLL.Migrations
{
    [DbContext(typeof(BillContext))]
    partial class BillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FinancesAppDLL.Models.Bills", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShopsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("buydate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("money")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ShopsId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("FinancesAppDLL.Models.People", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("FinancesAppDLL.Models.Shops", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("FinancesAppDLL.Models.Bills", b =>
                {
                    b.HasOne("FinancesAppDLL.Models.People", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancesAppDLL.Models.Shops", "Shops")
                        .WithMany()
                        .HasForeignKey("ShopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Shops");
                });
#pragma warning restore 612, 618
        }
    }
}
